// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#ifndef _LFP_DEVICE_UI_SQUARELINESTUDIO_UI_H
#define _LFP_DEVICE_UI_SQUARELINESTUDIO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "ui_Questions.h"
#include "ui_Home.h"
#include "ui_WaitOrClick.h"
#include "ui_Confirm.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
