// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#include "ui.h"

lv_obj_t * ui_Confirm = NULL;
lv_obj_t * ui_arcConfirmFull = NULL;
lv_obj_t * ui_lblConfirmInstruction = NULL;
lv_obj_t * ui_lblConfirmSend = NULL;
// event funtions

// build funtions

void ui_Confirm_screen_init(void)
{
    ui_Confirm = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Confirm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Confirm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Confirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcConfirmFull = lv_arc_create(ui_Confirm);
    lv_obj_set_width(ui_arcConfirmFull, lv_pct(95));
    lv_obj_set_height(ui_arcConfirmFull, lv_pct(95));
    lv_obj_set_x(ui_arcConfirmFull, 0);
    lv_obj_set_y(ui_arcConfirmFull, 2);
    lv_obj_set_align(ui_arcConfirmFull, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcConfirmFull, 0, 5);
    lv_arc_set_value(ui_arcConfirmFull, 5);
    lv_arc_set_bg_angles(ui_arcConfirmFull, 180, 0);
    lv_obj_set_style_arc_color(ui_arcConfirmFull, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcConfirmFull, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcConfirmFull, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_arcConfirmFull, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Primary_Red);
    ui_object_set_themeable_style_property(ui_arcConfirmFull, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Primary_Red);
    lv_obj_set_style_arc_width(ui_arcConfirmFull, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_arcConfirmFull, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Light_Gray);
    ui_object_set_themeable_style_property(ui_arcConfirmFull, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Light_Gray);
    lv_obj_set_style_border_color(ui_arcConfirmFull, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcConfirmFull, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcConfirmFull, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblConfirmInstruction = lv_label_create(ui_Confirm);
    lv_obj_set_width(ui_lblConfirmInstruction, lv_pct(60));
    lv_obj_set_height(ui_lblConfirmInstruction, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_lblConfirmInstruction, lv_pct(0));
    lv_obj_set_y(ui_lblConfirmInstruction, lv_pct(-2));
    lv_obj_set_align(ui_lblConfirmInstruction, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblConfirmInstruction, "Are you sure?");
    lv_obj_set_style_text_align(ui_lblConfirmInstruction, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblConfirmInstruction, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblConfirmSend = lv_label_create(ui_Confirm);
    lv_obj_set_width(ui_lblConfirmSend, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_lblConfirmSend, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_lblConfirmSend, lv_pct(-3));
    lv_obj_set_y(ui_lblConfirmSend, lv_pct(26));
    lv_obj_set_align(ui_lblConfirmSend, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblConfirmSend, "SEND");
    lv_obj_set_style_text_align(ui_lblConfirmSend, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblConfirmSend, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_lblConfirmSend, 300, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Confirm_screen_destroy(void)
{
    if(ui_Confirm) lv_obj_del(ui_Confirm);

    // NULL screen variables
    ui_Confirm = NULL;
    ui_arcConfirmFull = NULL;
    ui_lblConfirmInstruction = NULL;
    ui_lblConfirmSend = NULL;

}
