// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#ifndef UI_CONFIRM_H
#define UI_CONFIRM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Confirm
extern void ui_Confirm_screen_init(void);
extern void ui_Confirm_screen_destroy(void);
extern lv_obj_t * ui_Confirm;
extern lv_obj_t * ui_arcConfirmFull;
extern lv_obj_t * ui_lblConfirmInstruction;
extern lv_obj_t * ui_lblConfirmSend;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

