// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: questionScreen

#include "ui.h"

// COMPONENT splashAnim

lv_obj_t * ui_splashAnim_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_splashAnim;
    cui_splashAnim = lv_img_create(comp_parent);
    lv_obj_set_width(cui_splashAnim, 1920);
    lv_obj_set_height(cui_splashAnim, LV_SIZE_CONTENT);    /// 1080
    lv_obj_set_x(cui_splashAnim, 0);
    lv_obj_set_y(cui_splashAnim, -86);
    lv_obj_set_align(cui_splashAnim, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_splashAnim, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_splashAnim, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_splashAnim, 100);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SPLASHANIM_NUM);
    children[UI_COMP_SPLASHANIM_SPLASHANIM] = cui_splashAnim;
    lv_obj_add_event_cb(cui_splashAnim, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_splashAnim, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_splashAnim_create_hook(cui_splashAnim);
    return cui_splashAnim;
}

