// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#include "ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_lblHomeNFC = NULL;
// event funtions

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHomeNFC = lv_label_create(ui_Home);
    lv_obj_set_width(ui_lblHomeNFC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHomeNFC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHomeNFC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHomeNFC, "NFC");
    lv_obj_set_style_text_font(ui_lblHomeNFC, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_lblHomeNFC = NULL;

}
