// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: questionScreen

#ifndef UI_QUESTIONSCREEN1_H
#define UI_QUESTIONSCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_questionScreen1
extern void ui_questionScreen1_screen_init(void);
extern void ui_questionScreen1_screen_destroy(void);
extern lv_obj_t * ui_questionScreen1;
extern lv_obj_t * ui_lblQuestionStep1;
extern lv_obj_t * ui_arcQuestionProgress1;
extern lv_obj_t * ui_lblQuestionText1;
extern lv_obj_t * ui_lblCurrentOption1;
extern lv_obj_t * ui_lblPrevOption1;
extern lv_obj_t * ui_lblNextOption1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

