// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#ifndef UI_QUESTIONS_H
#define UI_QUESTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Questions
extern void ui_Questions_screen_init(void);
extern void ui_Questions_screen_destroy(void);
extern lv_obj_t * ui_Questions;
extern lv_obj_t * ui_lblQuestionsNumeration;
extern lv_obj_t * ui_arcQuestionsProgress;
extern lv_obj_t * ui_lblQuestionsInstruction;
extern lv_obj_t * ui_lblQuestionsCurrentOption;
extern lv_obj_t * ui_lblQuestionsPrevOption;
extern lv_obj_t * ui_lblQuestionsNextOption;
extern lv_obj_t * ui_lblQuestionsType;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

