// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: questionScreen

#include "ui.h"

lv_obj_t * ui_questionScreen1 = NULL;
lv_obj_t * ui_lblQuestionStep1 = NULL;
lv_obj_t * ui_arcQuestionProgress1 = NULL;
lv_obj_t * ui_lblQuestionText1 = NULL;
lv_obj_t * ui_lblCurrentOption1 = NULL;
lv_obj_t * ui_lblPrevOption1 = NULL;
lv_obj_t * ui_lblNextOption1 = NULL;
// event funtions

// build funtions

void ui_questionScreen1_screen_init(void)
{
    ui_questionScreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_questionScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_questionScreen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_questionScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblQuestionStep1 = lv_label_create(ui_questionScreen1);
    lv_obj_set_width(ui_lblQuestionStep1, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_lblQuestionStep1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblQuestionStep1, 0);
    lv_obj_set_y(ui_lblQuestionStep1, lv_pct(-20));
    lv_obj_set_align(ui_lblQuestionStep1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblQuestionStep1, "Q 1/5");
    lv_obj_set_style_text_font(ui_lblQuestionStep1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcQuestionProgress1 = lv_arc_create(ui_questionScreen1);
    lv_obj_set_width(ui_arcQuestionProgress1, lv_pct(95));
    lv_obj_set_height(ui_arcQuestionProgress1, lv_pct(95));
    lv_obj_set_x(ui_arcQuestionProgress1, 0);
    lv_obj_set_y(ui_arcQuestionProgress1, 2);
    lv_obj_set_align(ui_arcQuestionProgress1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcQuestionProgress1, 0, 5);
    lv_arc_set_value(ui_arcQuestionProgress1, 1);
    lv_arc_set_bg_angles(ui_arcQuestionProgress1, 180, 0);
    lv_obj_set_style_arc_color(ui_arcQuestionProgress1, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcQuestionProgress1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcQuestionProgress1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arcQuestionProgress1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcQuestionProgress1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcQuestionProgress1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcQuestionProgress1, lv_color_hex(0xFF1111), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcQuestionProgress1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_arcQuestionProgress1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcQuestionProgress1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcQuestionProgress1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblQuestionText1 = lv_label_create(ui_questionScreen1);
    lv_obj_set_width(ui_lblQuestionText1, lv_pct(60));
    lv_obj_set_height(ui_lblQuestionText1, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_lblQuestionText1, lv_pct(0));
    lv_obj_set_y(ui_lblQuestionText1, lv_pct(5));
    lv_obj_set_align(ui_lblQuestionText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblQuestionText1, "How would you rate J&J on innovation?");
    lv_obj_set_style_text_align(ui_lblQuestionText1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblQuestionText1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCurrentOption1 = lv_label_create(ui_questionScreen1);
    lv_obj_set_width(ui_lblCurrentOption1, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_lblCurrentOption1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_lblCurrentOption1, lv_pct(0));
    lv_obj_set_y(ui_lblCurrentOption1, lv_pct(35));
    lv_obj_set_align(ui_lblCurrentOption1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCurrentOption1, "3");
    lv_obj_set_style_text_align(ui_lblCurrentOption1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCurrentOption1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPrevOption1 = lv_label_create(ui_questionScreen1);
    lv_obj_set_width(ui_lblPrevOption1, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_lblPrevOption1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPrevOption1, lv_pct(-30));
    lv_obj_set_y(ui_lblPrevOption1, lv_pct(30));
    lv_obj_set_align(ui_lblPrevOption1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPrevOption1, "2");
    lv_obj_set_style_text_color(ui_lblPrevOption1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPrevOption1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblPrevOption1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPrevOption1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNextOption1 = lv_label_create(ui_questionScreen1);
    lv_obj_set_width(ui_lblNextOption1, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_lblNextOption1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNextOption1, lv_pct(30));
    lv_obj_set_y(ui_lblNextOption1, lv_pct(30));
    lv_obj_set_align(ui_lblNextOption1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNextOption1, "4");
    lv_obj_set_style_text_color(ui_lblNextOption1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNextOption1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblNextOption1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNextOption1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_questionScreen1_screen_destroy(void)
{
    if(ui_questionScreen1) lv_obj_del(ui_questionScreen1);

    // NULL screen variables
    ui_questionScreen1 = NULL;
    ui_lblQuestionStep1 = NULL;
    ui_arcQuestionProgress1 = NULL;
    ui_lblQuestionText1 = NULL;
    ui_lblCurrentOption1 = NULL;
    ui_lblPrevOption1 = NULL;
    ui_lblNextOption1 = NULL;

}
