// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#include "ui.h"

lv_obj_t * ui_Questions = NULL;
lv_obj_t * ui_lblQuestionsNumeration = NULL;
lv_obj_t * ui_arcQuestionsProgress = NULL;
lv_obj_t * ui_lblQuestionsInstruction = NULL;
lv_obj_t * ui_lblQuestionsCurrentOption = NULL;
lv_obj_t * ui_lblQuestionsPrevOption = NULL;
lv_obj_t * ui_lblQuestionsNextOption = NULL;
lv_obj_t * ui_lblQuestionsType = NULL;
// event funtions

// build funtions

void ui_Questions_screen_init(void)
{
    ui_Questions = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Questions, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Questions, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Questions, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblQuestionsNumeration = lv_label_create(ui_Questions);
    lv_obj_set_width(ui_lblQuestionsNumeration, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_lblQuestionsNumeration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblQuestionsNumeration, -2);
    lv_obj_set_y(ui_lblQuestionsNumeration, lv_pct(-30));
    lv_obj_set_align(ui_lblQuestionsNumeration, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblQuestionsNumeration, "1/5");
    lv_obj_set_style_text_color(ui_lblQuestionsNumeration, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblQuestionsNumeration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblQuestionsNumeration, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcQuestionsProgress = lv_arc_create(ui_Questions);
    lv_obj_set_width(ui_arcQuestionsProgress, lv_pct(95));
    lv_obj_set_height(ui_arcQuestionsProgress, lv_pct(95));
    lv_obj_set_x(ui_arcQuestionsProgress, 0);
    lv_obj_set_y(ui_arcQuestionsProgress, 2);
    lv_obj_set_align(ui_arcQuestionsProgress, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcQuestionsProgress, 0, 5);
    lv_arc_set_value(ui_arcQuestionsProgress, 1);
    lv_arc_set_bg_angles(ui_arcQuestionsProgress, 180, 0);
    lv_obj_set_style_arc_color(ui_arcQuestionsProgress, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcQuestionsProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcQuestionsProgress, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_arcQuestionsProgress, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_ARC_COLOR, _ui_theme_color_Primary_Red);
    ui_object_set_themeable_style_property(ui_arcQuestionsProgress, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Primary_Red);
    lv_obj_set_style_arc_width(ui_arcQuestionsProgress, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_arcQuestionsProgress, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Light_Gray);
    ui_object_set_themeable_style_property(ui_arcQuestionsProgress, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Light_Gray);
    lv_obj_set_style_border_color(ui_arcQuestionsProgress, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcQuestionsProgress, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcQuestionsProgress, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblQuestionsInstruction = lv_label_create(ui_Questions);
    lv_obj_set_width(ui_lblQuestionsInstruction, lv_pct(60));
    lv_obj_set_height(ui_lblQuestionsInstruction, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_lblQuestionsInstruction, lv_pct(0));
    lv_obj_set_y(ui_lblQuestionsInstruction, lv_pct(5));
    lv_obj_set_align(ui_lblQuestionsInstruction, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblQuestionsInstruction, "Lorem ipsum dolor sit amet, elit sed amet ?");
    lv_obj_set_style_text_align(ui_lblQuestionsInstruction, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblQuestionsInstruction, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblQuestionsCurrentOption = lv_label_create(ui_Questions);
    lv_obj_set_width(ui_lblQuestionsCurrentOption, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_lblQuestionsCurrentOption, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_lblQuestionsCurrentOption, lv_pct(0));
    lv_obj_set_y(ui_lblQuestionsCurrentOption, lv_pct(35));
    lv_obj_set_align(ui_lblQuestionsCurrentOption, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblQuestionsCurrentOption, "3");
    lv_obj_set_style_text_align(ui_lblQuestionsCurrentOption, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblQuestionsCurrentOption, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_lblQuestionsCurrentOption, 300, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblQuestionsPrevOption = lv_label_create(ui_Questions);
    lv_obj_set_width(ui_lblQuestionsPrevOption, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_lblQuestionsPrevOption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblQuestionsPrevOption, lv_pct(-30));
    lv_obj_set_y(ui_lblQuestionsPrevOption, lv_pct(30));
    lv_obj_set_align(ui_lblQuestionsPrevOption, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblQuestionsPrevOption, "2");
    lv_obj_set_style_text_color(ui_lblQuestionsPrevOption, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblQuestionsPrevOption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblQuestionsPrevOption, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblQuestionsPrevOption, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblQuestionsNextOption = lv_label_create(ui_Questions);
    lv_obj_set_width(ui_lblQuestionsNextOption, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_lblQuestionsNextOption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblQuestionsNextOption, lv_pct(30));
    lv_obj_set_y(ui_lblQuestionsNextOption, lv_pct(30));
    lv_obj_set_align(ui_lblQuestionsNextOption, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblQuestionsNextOption, "4");
    lv_obj_set_style_text_color(ui_lblQuestionsNextOption, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblQuestionsNextOption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblQuestionsNextOption, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblQuestionsNextOption, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblQuestionsType = lv_label_create(ui_Questions);
    lv_obj_set_width(ui_lblQuestionsType, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_lblQuestionsType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblQuestionsType, 0);
    lv_obj_set_y(ui_lblQuestionsType, lv_pct(-20));
    lv_obj_set_align(ui_lblQuestionsType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblQuestionsType, "Question");
    lv_obj_set_style_text_color(ui_lblQuestionsType, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblQuestionsType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblQuestionsType, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Questions_screen_destroy(void)
{
    if(ui_Questions) lv_obj_del(ui_Questions);

    // NULL screen variables
    ui_Questions = NULL;
    ui_lblQuestionsNumeration = NULL;
    ui_arcQuestionsProgress = NULL;
    ui_lblQuestionsInstruction = NULL;
    ui_lblQuestionsCurrentOption = NULL;
    ui_lblQuestionsPrevOption = NULL;
    ui_lblQuestionsNextOption = NULL;
    ui_lblQuestionsType = NULL;

}
