// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Primary_Red[3] = {0xD71500, 0xD71500, 0xD71500};
const ui_theme_variable_t _ui_theme_alpha_Primary_Red[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Dark_Red[3] = {0xA51200, 0xA51200, 0xA51200};
const ui_theme_variable_t _ui_theme_alpha_Dark_Red[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Light_Red[3] = {0xEB1700, 0xEB1700, 0xEB1700};
const ui_theme_variable_t _ui_theme_alpha_Light_Red[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Charcoal[3] = {0x222222, 0x222222, 0x222222};
const ui_theme_variable_t _ui_theme_alpha_Charcoal[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Light_Gray[3] = {0xF5F5F5, 0xF5F5F5, 0xF5F5F5};
const ui_theme_variable_t _ui_theme_alpha_Light_Gray[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_JOHNSON;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

