// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_PRIMARY_RED 0
#define UI_THEME_COLOR_DARK_RED 1
#define UI_THEME_COLOR_LIGHT_RED 2
#define UI_THEME_COLOR_CHARCOAL 3
#define UI_THEME_COLOR_LIGHT_GRAY 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_DARK 1

#define UI_THEME_JOHNSON 2

extern const ui_theme_variable_t _ui_theme_color_Primary_Red[3];
extern const ui_theme_variable_t _ui_theme_alpha_Primary_Red[3];

extern const ui_theme_variable_t _ui_theme_color_Dark_Red[3];
extern const ui_theme_variable_t _ui_theme_alpha_Dark_Red[3];

extern const ui_theme_variable_t _ui_theme_color_Light_Red[3];
extern const ui_theme_variable_t _ui_theme_alpha_Light_Red[3];

extern const ui_theme_variable_t _ui_theme_color_Charcoal[3];
extern const ui_theme_variable_t _ui_theme_alpha_Charcoal[3];

extern const ui_theme_variable_t _ui_theme_color_Light_Gray[3];
extern const ui_theme_variable_t _ui_theme_alpha_Light_Gray[3];

extern const uint32_t * ui_theme_colors[3];
extern const uint8_t * ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
