// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#ifndef UI_WAITORCLICK_H
#define UI_WAITORCLICK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WaitOrClick
extern void ui_WaitOrClick_screen_init(void);
extern void ui_WaitOrClick_screen_destroy(void);
extern lv_obj_t * ui_WaitOrClick;
extern lv_obj_t * ui_arcWaitOrClick;
extern lv_obj_t * ui_lblWaitOrClick;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

