// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LFP-DEVICE_UI_SquareLineStudio

#include "ui.h"

lv_obj_t * ui_WaitOrClick = NULL;
lv_obj_t * ui_arcWaitOrClick = NULL;
lv_obj_t * ui_lblWaitOrClick = NULL;
// event funtions

// build funtions

void ui_WaitOrClick_screen_init(void)
{
    ui_WaitOrClick = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WaitOrClick, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WaitOrClick, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaitOrClick, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcWaitOrClick = lv_arc_create(ui_WaitOrClick);
    lv_obj_set_width(ui_arcWaitOrClick, lv_pct(80));
    lv_obj_set_height(ui_arcWaitOrClick, lv_pct(80));
    lv_obj_set_align(ui_arcWaitOrClick, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_arcWaitOrClick, 20);
    lv_arc_set_bg_angles(ui_arcWaitOrClick, 0, 360);
    lv_arc_set_rotation(ui_arcWaitOrClick, 90);

    ui_object_set_themeable_style_property(ui_arcWaitOrClick, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Dark_Red);
    ui_object_set_themeable_style_property(ui_arcWaitOrClick, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Dark_Red);

    ui_object_set_themeable_style_property(ui_arcWaitOrClick, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Light_Red);
    ui_object_set_themeable_style_property(ui_arcWaitOrClick, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Light_Red);

    ui_lblWaitOrClick = lv_label_create(ui_WaitOrClick);
    lv_obj_set_width(ui_lblWaitOrClick, lv_pct(60));
    lv_obj_set_height(ui_lblWaitOrClick, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_lblWaitOrClick, lv_pct(1));
    lv_obj_set_y(ui_lblWaitOrClick, lv_pct(-1));
    lv_obj_set_align(ui_lblWaitOrClick, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWaitOrClick, "Thanks!\n\nFind yourself\nat the bigger\nscreen.");
    lv_obj_set_style_text_align(ui_lblWaitOrClick, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWaitOrClick, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_WaitOrClick_screen_destroy(void)
{
    if(ui_WaitOrClick) lv_obj_del(ui_WaitOrClick);

    // NULL screen variables
    ui_WaitOrClick = NULL;
    ui_arcWaitOrClick = NULL;
    ui_lblWaitOrClick = NULL;

}
